### ISSUE TITLE
this is frontend not backend

### ISSUE THREAD

**Issue by 0xtrzy** [sundown/rib#1]
this not compiling to lisp

**Comment by Sundown** [comment]
> this not compiling to lisp

Thanks for the comment. As stated, this isn't complete. For ease during development I am supplying code to Rib by text file as shown in the readme. 
The eventual goal of this project (if I continue to develop it) is to provide an API for common abstractions required for functional languages to be compiled. 
As this project is currently incapable of its eventual goal, I have included references to LISP. 
The eventual process of Rib would look something like

API->[IR->LLVM->CLANG]->library. 

Making it a backend.
